version: "3.7"

services:  
  app:
    build: .
    container_name: dock_api
    ports: 
      - 3333:3333
    volumes: 
      - .:/usr/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes: 
  pgdata:
    driver: local